name = "Cobbleverse NeoForge Zen"
author = "Zen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c560b87e1c5ea00281b6d82a3019b6f52d966b80f5dd234011eb326976f1d6bb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1", "1.21", "1.20.1"]
