name = "Cobbleverse NeoForge Zen"
author = "Zen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9230685b224cf780a1cbb5d73bdae72d76b98f0dbd991c8f38b148d76168f4cb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1", "1.21", "1.20.1"]
