name = "Cobbleverse NeoForge Zen"
author = "Zen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "884da5b00f25fcb779f5f8d612c72a5a778c8cdce6f5f85586cef0c7b7e86d1c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1", "1.21", "1.20.1"]
